doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
            business_data:
                url: '%env(resolve:DATABASE_BUSINESS_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        #profiling_collect_backtrace: '%kernel.debug%'
        #use_savepoints: true
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    Main:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            business_data:
                connection: business_data
                auto_mapping: false
                mappings:
                    BusinessData:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/Entity/BusinessData'
                        prefix: 'App\Entity\BusinessData'
                        alias: BusinessData
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        #report_fields_where_declared: true
        #validate_xml_mapping: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        #auto_mapping: true
        #mappings:
            #App:
                #type: attribute
                #is_bundle: false
                #dir: '%kernel.project_dir%/src/Entity'
                #prefix: 'App\Entity'
                #alias: App

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
